# Generated by Django 3.2.9 on 2021-11-22 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211122_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='end',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='classes',
            old_name='start',
            new_name='endTime',
        ),
        migrations.AddField(
            model_name='classes',
            name='startDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classes',
            name='startTime',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
