# Generated by Django 3.2.9 on 2021-11-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_category_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
