# Generated by Django 3.2.9 on 2021-11-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20211128_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='special_offer',
            field=models.BooleanField(default=False, verbose_name='Special Offer?'),
        ),
    ]
