# Generated by Django 3.2.9 on 2021-12-28 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
    ]
