# Generated by Django 3.2.9 on 2021-12-31 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customer_phone_number'),
        ('order', '0007_auto_20211231_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_customer', to='account.customer'),
        ),
    ]
